# Copyright (C) 2015 Fabien Parent. All rights reserved.
# Author: Fabien Parent <parent.f@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-$(CONFIG_APP_LSDEV) += lsdev.o
obj-$(CONFIG_APP_FREE) += free.o
obj-$(CONFIG_APP_PS) += ps.o
obj-$(CONFIG_APP_I2C) += i2c.o
obj-$(CONFIG_APP_UNIPRO) += unipro.o
